c_compiler:                # [osx]
  - clang                  # [osx]
c_compiler_version:        # [osx]
  - 12                     # [osx]
cxx_compiler_version:      # [osx]
  - 12                     # [osx]