{% set name = "spacy-alignments" %}
{% set module_name = "spacy_alignments" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4702997f459d30e537f638fbb540151adfab88aa2969f9d0db3e3ba39f47bdb


build:
  number: 0
  # rust-gnu_win-32=1.56.0 and rust_win-32=1.56.0 aren't available on win32
  skip: True  # [py<36 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  missing_dso_whitelist:
    - $RPATH/ld64.so.1  # [linux and s390x]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - python

test:
  imports:
    - {{ module_name }}
  requires:
    - hypothesis >=5.3.1,<6.0.0
    - pip
    - pytest
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ module_name }}

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Align tokenizations for spaCy + transformers
  description: |
    A spaCy package for Yohei Tamura's Rust tokenizations library.
  doc_url: https://github.com/explosion/spacy-alignments
  dev_url: https://github.com/explosion/spacy-alignments

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
