{% set name = "spacy-alignments" %}
{% set module_name = "spacy_alignments" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc358821591f576eef7bfe10187bc7b06b9a0c438a1f346170638718eff1263

build:
  number: 0
  # 2022/4/27: On win64 `rust_compiler_rust-gnu` tries to create two artifacts with different hashes in the artifact's filename,
  # and testing one of them fails but another succeeded.
  skip: True  # [py<36 or win32 or (win64 and (rust_compiler == 'rust-gnu'))]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]
requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - python
    - pin_compatible("libgcc-ng", max_pin=None) # [linux]

test:
  requires:
    - hypothesis >=5.3.1,<7.0.0
    - pip
    - pytest
  imports:
    - {{ module_name }}
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ module_name }}

about:
  home: https://spacy.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Align tokenizations for spaCy + transformers
  description: |
    A spaCy package for Yohei Tamura's Rust tokenizations library.
  doc_url: https://github.com/explosion/spacy-alignments
  dev_url: https://github.com/explosion/spacy-alignments

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
