{% set name = "spacy-alignments" %}
{% set version = "0.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 1c50b50d261550d3220887cfd0a12a6e85e709d815a66949f6b92340e4278d69

build:
  number: 0
  # 2022/4/27: On win64 `rust_compiler_rust-gnu` tries to create two artifacts with different hashes in the artifact's filename,
  # and testing one of them fails but another succeeded.
  skip: true  # [py<39 or win32 or (win64 and (rust_compiler == 'rust-gnu'))]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - python
    - {{ pin_compatible("libgcc-ng", max_pin=None) }}  # [linux]

test:
  requires:
    - pip
    - pytest
    - hypothesis
  imports:
    - spacy_alignments
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv --tb=short --pyargs spacy_alignments

about:
  home: https://spacy.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Align tokenizations for spaCy + transformers
  description: |
    A spaCy package for Yohei Tamura's Rust tokenizations library.
  doc_url: https://github.com/explosion/spacy-alignments
  dev_url: https://github.com/explosion/spacy-alignments

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
